apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../../docker-compose.yml convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: core
    spec:
      containers:
      - env:
        - name: DEV_MODE
        - name: DOMAIN
          value: bbb.egauss.net
        - name: SHARED_SECRET
          value: yVLQSPFNLhCzRWebzU470hBYNZ5b2ImZXXtaHLVB
        - name: STUN_SERVER
          value: stun:216.93.246.18:3478
        - name: TURN_SECRET
        - name: TURN_SERVER
        - name: WELCOME_FOOTER
        - name: WELCOME_MESSAGE
        image: core
        name: core
        resources: {}
        volumeMounts:
        - mountPath: /var/bigbluebutton
          name: bigbluebutton
      restartPolicy: Always
      volumes:
      - name: bigbluebutton
        persistentVolumeClaim:
          claimName: bigbluebutton
status: {}
