apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../../docker-compose.greenlight.yml convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: greenlight
  name: greenlight
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  selector:
    io.kompose.service: greenlight
status:
  loadBalancer: {}
