apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../../docker-compose.yml convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webrtc-sfu
  name: webrtc-sfu
spec:
  ports:
  - name: "3008"
    port: 3008
    targetPort: 3008
  selector:
    io.kompose.service: webrtc-sfu
status:
  loadBalancer: {}
